"""Semantic (vector) search over knowledge-base chunks.

Embeddings are generated by the ``embed`` pipeline and stored in pgvector.
This module embeds a query with the same provider and finds nearest neighbours
using cosine distance, ranked by similarity score.  Every hit carries full
book / chapter / section / page / source provenance so that vector search
never loses traceability.
"""

from __future__ import annotations

from collections.abc import Sequence
from dataclasses import dataclass
from typing import Protocol

from sqlalchemy import select
from sqlalchemy.orm import Session

from knowledge_base.database.enums import Language, SourceFormat
from knowledge_base.database.models.books import Author, Book, Category
from knowledge_base.database.models.embeddings import Embedding, EmbeddingModel
from knowledge_base.database.models.sources import SourceFile
from knowledge_base.database.models.structure import Chapter, ContentChunk, Section


@dataclass(frozen=True)
class VectorHit:
    """One semantic search result with full provenance."""

    score: float
    text: str
    chunk_id: str
    content_id: str
    book: str
    book_id: str
    author: str | None = None
    category: str | None = None
    chapter: str | None = None
    chapter_id: str | None = None
    section: str | None = None
    section_id: str | None = None
    page: int | None = None
    source: str | None = None
    source_id: str | None = None
    source_type: str | None = None
    language: str | None = None


_LANG_MAP = {
    "ar": Language.ARABIC,
    "ur": Language.URDU,
    "en": Language.ENGLISH,
}

_SOURCE_FORMAT_MAP = {v.value: v for v in SourceFormat}


class _QueryEmbedder(Protocol):
    """Minimal embed interface used to embed a search query."""

    dimensions: int
    name: str
    version: str

    def embed(self, texts: Sequence[str]) -> list[list[float]]: ...


def _resolve_model(
    session: Session,
    model_name: str,
    model_version: str | None,
) -> EmbeddingModel | None:
    q = select(EmbeddingModel).where(EmbeddingModel.name == model_name)
    if model_version:
        q = q.where(EmbeddingModel.version == model_version)
    else:
        q = q.order_by(EmbeddingModel.version.desc()).limit(1)
    return session.execute(q).scalar_one_or_none()


def similar(
    session: Session,
    query_text: str,
    provider: _QueryEmbedder,
    *,
    model_name: str,
    model_version: str | None = None,
    limit: int = 20,
    category: str | None = None,
    source: str | None = None,
    language: str | None = None,
    source_type: str | None = None,
    author: str | None = None,
    min_score: float | None = None,
) -> list[VectorHit]:
    """Find chunks semantically similar to *query_text*.

    Parameters
    ----------
    provider:
        An ``EmbeddingProvider`` instance (has ``embed``, ``dimensions``,
        ``name``, ``version`` attributes) used to embed the query.
    model_name / model_version:
        Scope results to a specific embedding model.  *model_version* is
        optional; when omitted the latest version for *model_name* is used.

    Returns
    -------
    list[VectorHit]
        Results ranked by descending cosine similarity score.
    """
    if not query_text or not query_text.strip():
        return []

    model = _resolve_model(session, model_name, model_version)
    if model is None:
        return []

    if provider.dimensions != model.dimensions:
        raise ValueError(
            f"Provider dimensions ({provider.dimensions}) "
            f"do not match model dimensions ({model.dimensions})"
        )

    query_vec = provider.embed([query_text])[0]

    distance = Embedding.vector.cosine_distance(query_vec)
    score_expr = (1.0 - distance).label("score")

    stmt = (
        select(
            ContentChunk,
            Book,
            SourceFile,
            Chapter,
            Section,
            Author,
            Category,
            score_expr,
        )
        .join(Embedding, Embedding.content_chunk_id == ContentChunk.id)
        .join(EmbeddingModel, Embedding.model_id == EmbeddingModel.id)
        .join(Book, ContentChunk.book_id == Book.id)
        .join(SourceFile, Book.source_file_id == SourceFile.id)
        .outerjoin(Chapter, ContentChunk.chapter_id == Chapter.id)
        .outerjoin(Section, ContentChunk.section_id == Section.id)
        .outerjoin(Author, Book.author_id == Author.id)
        .outerjoin(Category, Book.category_id == Category.id)
        .where(EmbeddingModel.id == model.id)
    )

    if language:
        lang_enum = _LANG_MAP.get(language)
        if lang_enum is not None:
            stmt = stmt.where(ContentChunk.language == lang_enum)

    if source_type:
        fmt = _SOURCE_FORMAT_MAP.get(source_type)
        if fmt is not None:
            stmt = stmt.where(SourceFile.format == fmt)

    if source:
        stmt = stmt.where(SourceFile.sha256.startswith(source))

    if category:
        stmt = stmt.where(Category.code == category)

    if author:
        stmt = stmt.where(Author.name.ilike(f"%{author}%"))

    stmt = stmt.order_by(distance.asc()).limit(limit)

    rows = session.execute(stmt).all()

    hits: list[VectorHit] = []
    for chunk, book, sf, chapter, section, author_row, category_row, score_val in rows:
        s = float(score_val or 0.0)
        if min_score is not None and s < min_score:
            continue
        hits.append(
            VectorHit(
                score=s,
                text=chunk.text,
                chunk_id=chunk.chunk_id,
                content_id=str(chunk.id),
                book=book.title,
                book_id=str(book.id),
                author=author_row.name if author_row else None,
                category=category_row.code if category_row else None,
                chapter=chapter.title if chapter else None,
                chapter_id=str(chapter.id) if chapter else None,
                section=section.title if section else None,
                section_id=str(section.id) if section else None,
                page=chunk.page_start or chunk.page_end,
                source=sf.sha256,
                source_id=str(sf.id),
                source_type=sf.format.value,
                language=chunk.language.value,
            )
        )
    return hits


__all__ = ["VectorHit", "similar"]
