"""initial schema

Revision ID: 20441164e13e
Revises: 
Create Date: 2026-09-12 23:18:25.541581

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from pgvector.sqlalchemy import Vector

# revision identifiers, used by Alembic.
revision: str = '20441164e13e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('authors',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('name_arabic', sa.String(length=255), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', name='uq_authors_name')
    )
    op.create_table('categories',
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code', name='uq_categories_code')
    )
    op.create_table('embedding_models',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('provider', sa.String(length=255), nullable=True),
    sa.Column('dimensions', sa.Integer(), nullable=False),
    sa.Column('version', sa.String(length=64), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'version', name='uq_embedding_models_name_version')
    )
    op.create_table('hadith_collections',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('author', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', name='uq_hadith_collections_name')
    )
    op.create_table('publishers',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('city', sa.String(length=255), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', name='uq_publishers_name')
    )
    op.create_table('source_files',
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('file_path', sa.Text(), nullable=False),
    sa.Column('format', sa.Enum('pdf', 'epub', 'docx', 'txt', 'html', 'json', name='kb_sourceformat'), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('registered', 'processing', 'processed', 'failed', 'quarantined', name='kb_sourcestatus'), nullable=False),
    sa.Column('title_hint', sa.Text(), nullable=True),
    sa.Column('language_hint', sa.String(length=16), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sha256', name='uq_source_files_sha256')
    )
    op.create_index('ix_source_files_status', 'source_files', ['status'], unique=False)
    op.create_table('surahs',
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('name_arabic', sa.String(length=255), nullable=False),
    sa.Column('name_en', sa.String(length=255), nullable=True),
    sa.Column('name_transliteration', sa.String(length=255), nullable=True),
    sa.Column('ayah_count', sa.Integer(), nullable=True),
    sa.Column('revelation_place', sa.String(length=32), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('number', name='uq_surahs_number')
    )
    op.create_table('translators',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', name='uq_translators_name')
    )
    op.create_table('ayahs',
    sa.Column('surah_id', sa.Uuid(), nullable=False),
    sa.Column('source_file_id', sa.Uuid(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('page_number', sa.Integer(), nullable=True),
    sa.Column('juz', sa.Integer(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['source_file_id'], ['source_files.id'], ),
    sa.ForeignKeyConstraint(['surah_id'], ['surahs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('surah_id', 'number', name='uq_ayahs_surah_number')
    )
    op.create_index('ix_ayahs_number', 'ayahs', ['number'], unique=False)
    op.create_index('ix_ayahs_surah_id', 'ayahs', ['surah_id'], unique=False)
    op.create_table('hadith_books',
    sa.Column('collection_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['collection_id'], ['hadith_collections.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('collection_id', 'name', name='uq_hadith_books_collection_name')
    )
    op.create_index('ix_hadith_books_collection_id', 'hadith_books', ['collection_id'], unique=False)
    op.create_table('licenses',
    sa.Column('source_file_id', sa.Uuid(), nullable=False),
    sa.Column('license_type', sa.Enum('public_domain', 'copyrighted', 'cc_by', 'cc_by_sa', 'cc_by_nc', 'other', 'unknown', name='kb_licensetype'), nullable=False),
    sa.Column('holder', sa.String(length=255), nullable=True),
    sa.Column('granted_at', sa.DateTime(), nullable=True),
    sa.Column('expiry_at', sa.DateTime(), nullable=True),
    sa.Column('rights', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['source_file_id'], ['source_files.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_file_id', 'license_type', name='uq_licenses_file_type')
    )
    op.create_table('processing_jobs',
    sa.Column('source_file_id', sa.Uuid(), nullable=False),
    sa.Column('job_type', sa.Enum('ingest', 'inspect', 'extract', 'ocr', 'metadata', 'structure', 'normalize', 'chunk', 'index', 'embed', 'validate', name='kb_jobtype'), nullable=False),
    sa.Column('status', sa.Enum('pending', 'running', 'succeeded', 'failed', name='kb_jobstatus'), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('manifest', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'"), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['source_file_id'], ['source_files.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_file_id', 'job_type', name='uq_processing_jobs_file_type')
    )
    op.create_index('ix_processing_jobs_status', 'processing_jobs', ['status'], unique=False)
    op.create_table('source_editions',
    sa.Column('source_file_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('subtitle', sa.Text(), nullable=True),
    sa.Column('language', sa.String(length=16), nullable=True),
    sa.Column('publisher', sa.String(length=255), nullable=True),
    sa.Column('publication_year', sa.Integer(), nullable=True),
    sa.Column('isbn', sa.String(length=32), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['source_file_id'], ['source_files.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('isbn', name='uq_source_editions_isbn'),
    sa.UniqueConstraint('source_file_id', name='uq_source_editions_source_file')
    )
    op.create_table('topics',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('category_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('category_id', 'name', name='uq_topics_category_name'),
    sa.UniqueConstraint('name', name='uq_topics_name')
    )
    op.create_table('ayah_translations',
    sa.Column('ayah_id', sa.Uuid(), nullable=False),
    sa.Column('source_file_id', sa.Uuid(), nullable=False),
    sa.Column('language', sa.String(length=16), nullable=False),
    sa.Column('translator', sa.String(length=255), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['ayah_id'], ['ayahs.id'], ),
    sa.ForeignKeyConstraint(['source_file_id'], ['source_files.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ayah_id', 'language', 'translator', name='uq_ayah_trans_ayah_lang_tr')
    )
    op.create_index('ix_ayah_translations_language', 'ayah_translations', ['language'], unique=False)
    op.create_table('books',
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('subtitle', sa.Text(), nullable=True),
    sa.Column('language', sa.String(length=16), nullable=True),
    sa.Column('source_file_id', sa.Uuid(), nullable=False),
    sa.Column('edition_id', sa.Uuid(), nullable=True),
    sa.Column('author_id', sa.Uuid(), nullable=True),
    sa.Column('translator_id', sa.Uuid(), nullable=True),
    sa.Column('publisher_id', sa.Uuid(), nullable=True),
    sa.Column('category_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['authors.id'], ),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['edition_id'], ['source_editions.id'], ),
    sa.ForeignKeyConstraint(['publisher_id'], ['publishers.id'], ),
    sa.ForeignKeyConstraint(['source_file_id'], ['source_files.id'], ),
    sa.ForeignKeyConstraint(['translator_id'], ['translators.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_file_id', 'title', name='uq_books_source_title')
    )
    op.create_index('ix_books_category_id', 'books', ['category_id'], unique=False)
    op.create_table('hadith_chapters',
    sa.Column('collection_id', sa.Uuid(), nullable=False),
    sa.Column('hadith_book_id', sa.Uuid(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['collection_id'], ['hadith_collections.id'], ),
    sa.ForeignKeyConstraint(['hadith_book_id'], ['hadith_books.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('collection_id', 'name', name='uq_hadith_chapters_collection_name')
    )
    op.create_index('ix_hadith_chapters_collection_id', 'hadith_chapters', ['collection_id'], unique=False)
    op.create_table('book_topics',
    sa.Column('book_id', sa.Uuid(), nullable=False),
    sa.Column('topic_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], ),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ),
    sa.PrimaryKeyConstraint('book_id', 'topic_id')
    )
    op.create_table('chapters',
    sa.Column('book_id', sa.Uuid(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('source_file_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], ),
    sa.ForeignKeyConstraint(['source_file_id'], ['source_files.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('book_id', 'number', name='uq_chapters_book_number')
    )
    op.create_index('ix_chapters_book_id', 'chapters', ['book_id'], unique=False)
    op.create_table('hadiths',
    sa.Column('collection_id', sa.Uuid(), nullable=False),
    sa.Column('hadith_book_id', sa.Uuid(), nullable=True),
    sa.Column('hadith_chapter_id', sa.Uuid(), nullable=True),
    sa.Column('source_file_id', sa.Uuid(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('text_arabic', sa.Text(), nullable=True),
    sa.Column('grade', sa.String(length=255), nullable=True),
    sa.Column('narrator', sa.String(length=255), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['collection_id'], ['hadith_collections.id'], ),
    sa.ForeignKeyConstraint(['hadith_book_id'], ['hadith_books.id'], ),
    sa.ForeignKeyConstraint(['hadith_chapter_id'], ['hadith_chapters.id'], ),
    sa.ForeignKeyConstraint(['source_file_id'], ['source_files.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('collection_id', 'number', name='uq_hadiths_collection_number')
    )
    op.create_index('ix_hadiths_collection_id', 'hadiths', ['collection_id'], unique=False)
    op.create_index('ix_hadiths_hadith_chapter_id', 'hadiths', ['hadith_chapter_id'], unique=False)
    op.create_table('pages',
    sa.Column('book_id', sa.Uuid(), nullable=False),
    sa.Column('source_file_id', sa.Uuid(), nullable=False),
    sa.Column('page_number', sa.Integer(), nullable=False),
    sa.Column('has_text', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], ),
    sa.ForeignKeyConstraint(['source_file_id'], ['source_files.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('book_id', 'page_number', name='uq_pages_book_number')
    )
    op.create_index('ix_pages_source_file_id', 'pages', ['source_file_id'], unique=False)
    op.create_table('paragraphs',
    sa.Column('book_id', sa.Uuid(), nullable=False),
    sa.Column('page_id', sa.Uuid(), nullable=False),
    sa.Column('source_file_id', sa.Uuid(), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], ),
    sa.ForeignKeyConstraint(['page_id'], ['pages.id'], ),
    sa.ForeignKeyConstraint(['source_file_id'], ['source_files.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('book_id', 'page_id', 'sequence', name='uq_paragraphs_book_page_seq')
    )
    op.create_index('ix_paragraphs_page_id', 'paragraphs', ['page_id'], unique=False)
    op.create_table('sections',
    sa.Column('chapter_id', sa.Uuid(), nullable=False),
    sa.Column('book_id', sa.Uuid(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('source_file_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], ),
    sa.ForeignKeyConstraint(['chapter_id'], ['chapters.id'], ),
    sa.ForeignKeyConstraint(['source_file_id'], ['source_files.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('chapter_id', 'number', name='uq_sections_chapter_number')
    )
    op.create_index('ix_sections_chapter_id', 'sections', ['chapter_id'], unique=False)
    op.create_table('content_blocks',
    sa.Column('book_id', sa.Uuid(), nullable=False),
    sa.Column('page_id', sa.Uuid(), nullable=True),
    sa.Column('chapter_id', sa.Uuid(), nullable=True),
    sa.Column('section_id', sa.Uuid(), nullable=True),
    sa.Column('source_file_id', sa.Uuid(), nullable=False),
    sa.Column('block_type', sa.Enum('paragraph', 'heading', 'verse', 'hadith', 'footnote', 'page_header', 'other', name='kb_blocktype'), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('original_text', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'validated', 'review', 'published', 'quarantined', name='kb_contentstatus'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], ),
    sa.ForeignKeyConstraint(['chapter_id'], ['chapters.id'], ),
    sa.ForeignKeyConstraint(['page_id'], ['pages.id'], ),
    sa.ForeignKeyConstraint(['section_id'], ['sections.id'], ),
    sa.ForeignKeyConstraint(['source_file_id'], ['source_files.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('book_id', 'page_id', 'sequence', name='uq_blocks_book_page_seq')
    )
    op.create_index('ix_blocks_chapter_id', 'content_blocks', ['chapter_id'], unique=False)
    op.create_index('ix_blocks_page_id', 'content_blocks', ['page_id'], unique=False)
    op.create_table('content_chunks',
    sa.Column('chunk_id', sa.String(length=128), nullable=False),
    sa.Column('book_id', sa.Uuid(), nullable=False),
    sa.Column('content_block_id', sa.Uuid(), nullable=False),
    sa.Column('source_file_id', sa.Uuid(), nullable=False),
    sa.Column('page_number', sa.Integer(), nullable=True),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'validated', 'review', 'published', 'quarantined', name='kb_contentstatus'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], ),
    sa.ForeignKeyConstraint(['content_block_id'], ['content_blocks.id'], ),
    sa.ForeignKeyConstraint(['source_file_id'], ['source_files.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('chunk_id', name='uq_content_chunks_chunk_id'),
    sa.UniqueConstraint('content_block_id', 'sequence', name='uq_content_chunks_block_seq')
    )
    op.create_index('ix_content_chunks_book_id', 'content_chunks', ['book_id'], unique=False)
    op.create_table('embeddings',
    sa.Column('model_id', sa.Uuid(), nullable=False),
    sa.Column('content_chunk_id', sa.Uuid(), nullable=False),
    sa.Column('vector', Vector(768), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['content_chunk_id'], ['content_chunks.id'], ),
    sa.ForeignKeyConstraint(['model_id'], ['embedding_models.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('model_id', 'content_chunk_id', name='uq_embeddings_model_chunk')
    )
    op.create_index('ix_embeddings_content_chunk_id', 'embeddings', ['content_chunk_id'], unique=False)
    # HNSW approximate-nearest-neighbour index over PG vector columns.
    op.execute('CREATE INDEX ix_embeddings_vector_hnsw ON embeddings USING hnsw (vector vector_cosine_ops)')
    op.create_table('search_documents',
    sa.Column('content_chunk_id', sa.Uuid(), nullable=False),
    sa.Column('document_type', sa.String(length=32), nullable=False),
    sa.Column('language', sa.Enum('ar', 'ur', 'en', 'other', name='kb_language'), nullable=False),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('body_text', sa.Text(), nullable=False),
    sa.Column('search_vector', postgresql.TSVECTOR(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['content_chunk_id'], ['content_chunks.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('content_chunk_id', 'language', name='uq_search_docs_chunk_language')
    )
    op.create_index('ix_search_documents_language', 'search_documents', ['language'], unique=False)
    op.create_index('ix_search_documents_vector', 'search_documents', ['search_vector'], unique=False, postgresql_using='gin')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_search_documents_vector', table_name='search_documents', postgresql_using='gin')
    op.drop_index('ix_search_documents_language', table_name='search_documents')
    op.drop_table('search_documents')
    op.execute('DROP INDEX IF EXISTS ix_embeddings_vector_hnsw')
    op.drop_index('ix_embeddings_content_chunk_id', table_name='embeddings')
    op.drop_table('embeddings')
    op.drop_index('ix_content_chunks_book_id', table_name='content_chunks')
    op.drop_table('content_chunks')
    op.drop_index('ix_blocks_page_id', table_name='content_blocks')
    op.drop_index('ix_blocks_chapter_id', table_name='content_blocks')
    op.drop_table('content_blocks')
    op.drop_index('ix_sections_chapter_id', table_name='sections')
    op.drop_table('sections')
    op.drop_index('ix_paragraphs_page_id', table_name='paragraphs')
    op.drop_table('paragraphs')
    op.drop_index('ix_pages_source_file_id', table_name='pages')
    op.drop_table('pages')
    op.drop_index('ix_hadiths_hadith_chapter_id', table_name='hadiths')
    op.drop_index('ix_hadiths_collection_id', table_name='hadiths')
    op.drop_table('hadiths')
    op.drop_index('ix_chapters_book_id', table_name='chapters')
    op.drop_table('chapters')
    op.drop_table('book_topics')
    op.drop_index('ix_hadith_chapters_collection_id', table_name='hadith_chapters')
    op.drop_table('hadith_chapters')
    op.drop_index('ix_books_category_id', table_name='books')
    op.drop_table('books')
    op.drop_index('ix_ayah_translations_language', table_name='ayah_translations')
    op.drop_table('ayah_translations')
    op.drop_table('topics')
    op.drop_table('source_editions')
    op.drop_index('ix_processing_jobs_status', table_name='processing_jobs')
    op.drop_table('processing_jobs')
    op.drop_table('licenses')
    op.drop_index('ix_hadith_books_collection_id', table_name='hadith_books')
    op.drop_table('hadith_books')
    op.drop_index('ix_ayahs_surah_id', table_name='ayahs')
    op.drop_index('ix_ayahs_number', table_name='ayahs')
    op.drop_table('ayahs')
    op.drop_table('translators')
    op.drop_table('surahs')
    op.drop_index('ix_source_files_status', table_name='source_files')
    op.drop_table('source_files')
    op.drop_table('publishers')
    op.drop_table('hadith_collections')
    op.drop_table('embedding_models')
    op.drop_table('categories')
    op.drop_table('authors')
    # Drop the PostgreSQL ENUM types created by the migration (Alembic does
    # not remove them automatically).
    op.execute("DROP TYPE IF EXISTS kb_blocktype")
    op.execute("DROP TYPE IF EXISTS kb_contentstatus")
    op.execute("DROP TYPE IF EXISTS kb_jobstatus")
    op.execute("DROP TYPE IF EXISTS kb_jobtype")
    op.execute("DROP TYPE IF EXISTS kb_language")
    op.execute("DROP TYPE IF EXISTS kb_licensetype")
    op.execute("DROP TYPE IF EXISTS kb_sourceformat")
    op.execute("DROP TYPE IF EXISTS kb_sourcestatus")
    # ### end Alembic commands ###
