"""add metadata candidates

Revision ID: 44d8e71f7328
Revises: 75a57d77d004
Create Date: 2026-09-13 01:25:05.957777

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '44d8e71f7328'
down_revision: Union[str, Sequence[str], None] = '75a57d77d004'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('metadata_candidates',
    sa.Column('source_file_id', sa.Uuid(), nullable=False),
    sa.Column('field', sa.Enum('title', 'subtitle', 'author', 'translator', 'editor', 'publisher', 'publication_year', 'edition', 'language', 'isbn', 'category', 'description', 'page_count', name='kb_metadatafield'), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('confidence', sa.Enum('high', 'medium', 'low', name='kb_metadataconfidence'), nullable=False),
    sa.Column('uncertain', sa.Boolean(), nullable=False),
    sa.Column('source', sa.Enum('pdf_metadata', 'filename', 'first_pages', 'title_page', 'user_provided', name='kb_metadatasource'), nullable=False),
    sa.Column('evidence', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'review', 'approved', 'rejected', name='kb_metadatareviewstatus'), nullable=False),
    sa.Column('review_note', sa.Text(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reviewed_by', sa.String(length=255), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['source_file_id'], ['source_files.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_metadata_candidates_file_field_status', 'metadata_candidates', ['source_file_id', 'field', 'status'], unique=False)
    op.create_index('ix_metadata_candidates_status', 'metadata_candidates', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_metadata_candidates_status', table_name='metadata_candidates')
    op.drop_index('ix_metadata_candidates_file_field_status', table_name='metadata_candidates')
    op.drop_table('metadata_candidates')
    op.execute("DROP TYPE IF EXISTS kb_metadatafield")
    op.execute("DROP TYPE IF EXISTS kb_metadataconfidence")
    op.execute("DROP TYPE IF EXISTS kb_metadatasource")
    op.execute("DROP TYPE IF EXISTS kb_metadatareviewstatus")
    # ### end Alembic commands ###
